### PR TITLE
Fetching changes from Sleet origin fork

### PR DESCRIPTION
**Pull request by JohnTortugo**
Incorporating changes after this issue: https://github.com/emgarten/Sleet/issues/46

### CODE REVIEW

**Comment by emgarten** [comment]
You should take this one also. Which was just merged to master: https://github.com/emgarten/Sleet/pull/56

For a feed of your size you might end up hitting this.

**Comment by emgarten** [comment]
This contains fixes to reduce the amount of JSON-LD prettifying done, but if you don't care about this at all you can disable it completely by making this format method returning the same JObject back, and nooping.

https://github.com/jcagme/Sleet/blob/38bd7398a52d65c9a7d83923cdb23127dac73841/src/SleetLib/Common/JsonLDTokenComparer.cs#L23-L45

In you scenario this might be worth it.

**Comment by JohnTortugo** [comment]
Thanks @emgarten . I'll build + test this now.

**Comment by JohnTortugo** [comment]
I'm getting a type not found error:

`AmazonS3TestContext.cs(42,16): error CS0246: The type or namespace name 'AmazonS3FileSystem' could not be found (are you missing a using directive or an assembly reference?) [E:\Sleet\test\Sleet.AmazonS3.Tests\Sleet.AmazonS3.Tests.csproj]`

Which nuget does this come from?

**Comment by emgarten** [comment]
S3 support is disabled when SLEETLEGACY is set, which I think might apply to your fork.

https://github.com/emgarten/Sleet/blob/f0b766fc46f480c855dbe604eff64f4b2c26aac2/src/SleetLib/FileSystem/AmazonS3FileSystem.cs#L1

You can remove the if defs, or remove those tests if you only need azure support.

Or enable it all, I think I took this out for legacy, which was only used to bring in an older version of newtonsoft.json. It shouldn't have any negative impact if you build S3 support also, just more dependencies.

**Review by jcagme — APPROVED** [review]

**Pull request merged**
