### PR TITLE
Update config.props

### PR DESCRIPTION
**Pull request by JohnTortugo**
Update NuGet packages version to match what's used in Arcade

### CODE REVIEW

**Comment by jcagme** [comment]
Have we tested this all the way? This could break in Arcade and in repos consuming it so we need to make sure this is tested thoroughly. 

Is the original failure still happening or it was a transient error?

**Comment by JohnTortugo** [comment]
I tested this locally. I can create a package and test in other repos is that is needed.

The build that was originally failing was this one: https://dev.azure.com/dnceng/internal/_build?definitionId=480&_a=summary . The build passed after it started using an older version of Tasks.Feed

**Comment by jcagme** [comment]
If this is the actual fix I would suggest to test it in other repos before fully pushing this.

**Comment by jcagme** [comment]
Closed by mistake...

**Comment by JohnTortugo** [comment]
I'll create another PR

**Pull request closed without merging**
